spring.application.name=user-service
# MySQL Config
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/airbnb_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mysql}

# JPA Config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JWT
jwt.secret=${JWT_SECRET:mysecretkeymysecretkeymysecretkey}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# Actuator/Logging
management.endpoints.web.exposure.include=health,info
logging.level.org.springframework.security=INFO
logging.level.com.airbnb=INFO
